name: Integration test
on: push

jobs:
  build:
    name: Run example
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Simple Example
      uses: ./
      with:
        entrypoint: .github/workflows/run-example.sh
        args: simple
    - name: Run Stream Example
      uses: ./
      with:
        entrypoint: .github/workflows/run-example.sh
        args: stream

